version: "3.7"
services:
  app:
    image: gcc
    container_name: scrocrix-codeforces
    command: bash -c "while true; do sleep 1000; done"
    working_dir: /etc/local/codeforces
    volumes:
      - ./:/etc/local/codeforces
